s/j_comments/j_comments_ft/g
s/c_comments/c_comments_ft/g
s/cpp_comments/cpp_comments_ft/g
s/com_loc/com_loc_ft/g
s/prev_com_line/prev_com_line_ft/g
s/comment_skip/comment_skip_ft/g
s/lexclear/lexclear_ft/g
s/nsemi/nsemi_ft/g
s/operands/operands_ft/g
s/operators/operators_ft/g
s/sloc/sloc_ft/g
s/store_operand/store_operand_ft/g
s/store_operator/store_operator_ft/g
s/yy_buffer_state/yy_buffer_state_ft/g
s/yy_load_buffer_state/yy_load_buffer_state_ft/g
s/yy_switch_to_buffer/yy_switch_to_buffer_ft/g
s/yyin/yyin_ft/g
s/yyleng/yyleng_ft/g
s/yylex/yylex_ft/g
s/yyout/yyout_ft/g
s/yyrestart/yyrestart_ft/g
s/yytext/yytext_ft/g
s/yywrap/yywrap_ft/g
s/string_literal/string_literal_ft/g
/#include <unistd.h>/d
s/isatty(/_isatty(/g
s/fileno(/_fileno(/g
s/read(/_read(/g
