s/j_comments/j_comments_ht/g
s/c_comments/c_comments_ht/g
s/cpp_comments/cpp_comments_ht/g
s/com_loc/com_loc_ht/g
s/prev_com_line/prev_com_line_ht/g
s/comment_skip/comment_skip_ht/g
s/lexclear/lexclear_ht/g
s/nsemi/nsemi_ht/g
s/operands/operands_ht/g
s/operators/operators_ht/g
s/sloc/sloc_ht/g
s/slnat/slnat_ht/g
s/slhtm/slhtm_ht/g
s/slscr/slscr_ht/g
s/store_operand/store_operand_ht/g
s/store_operator/store_operator_ht/g
s/yy_buffer_state/yy_buffer_state_ht/g
s/yy_load_buffer_state/yy_load_buffer_state_ht/g
s/yy_switch_to_buffer/yy_switch_to_buffer_ht/g
s/yyin/yyin_ht/g
s/yyleng/yyleng_ht/g
s/yylex/yylex_ht/g
s/yyout/yyout_ht/g
s/yyrestart/yyrestart_ht/g
s/yytext/yytext_ht/g
s/yywrap/yywrap_ht/g
/#include <unistd.h>/d
s/isatty(/_isatty(/g
s/fileno(/_fileno(/g
s/read(/_read(/g
