s/j_comments/j_comments_mmp/g
s/c_comments/c_comments_mmp/g
s/cpp_comments/cpp_comments_mmp/g
s/com_loc/com_loc_mmp/g
s/comment_skip/comment_skip_mmp/g
s/lexclear/lexclear_mmp/g
s/nsemi/nsemi_mmp/g
s/ploc_count/ploc_count_mmp/g
s/operands/operands_mmp/g
s/operators/operators_mmp/g
s/sloc/sloc_mmp/g
s/store_operand/store_operand_mmp/g
s/store_operator/store_operator_mmp/g
s/yy_buffer_state/yy_buffer_state_mmp/g
s/yy_load_buffer_state/yy_load_buffer_state_mmp/g
s/yy_switch_to_buffer/yy_switch_to_buffer_mmp/g
s/yyin/yyin_mmp/g
s/yyleng/yyleng_mmp/g
s/yylex/yylex_mmp/g
s/yyout/yyout_mmp/g
s/yyrestart/yyrestart_mmp/g
s/yytext/yytext_mmp/g
s/yywrap/yywrap_mmp/g
s/string_literal/string_literal_mmp/g
/#include <unistd.h>/d
s/isatty(/_isatty(/g
s/fileno(/_fileno(/g
s/read(/_read(/g
