s/j_comments/j_comments_rb/g
s/c_comments/c_comments_rb/g
s/cpp_comments/cpp_comments_rb/g
s/com_loc/com_loc_rb/g
s/prev_com_line/prev_com_line_rb/g
s/comment_skip/comment_skip_rb/g
s/lexclear/lexclear_rb/g
s/nsemi/nsemi_rb/g
s/operands/operands_rb/g
s/operators/operators_rb/g
s/sloc/sloc_rb/g
s/store_operand/store_operand_rb/g
s/store_operator/store_operator_rb/g
s/yy_buffer_state/yy_buffer_state_rb/g
s/yy_load_buffer_state/yy_load_buffer_state_rb/g
s/yy_switch_to_buffer/yy_switch_to_buffer_rb/g
s/yyin/yyin_rb/g
s/yyleng/yyleng_rb/g
s/yylex/yylex_rb/g
s/yyout/yyout_rb/g
s/yyrestart/yyrestart_rb/g
s/yytext/yytext_rb/g
s/yywrap/yywrap_rb/g
s/string_literal/string_literal_rb/g
/#include <unistd.h>/d
s/isatty(/_isatty(/g
s/fileno(/_fileno(/g
s/read(/_read(/g
