/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Essential Project Manager (EPM)
 * Copyright (c) 2009 SourceCodeMetrics.com
 * Author Craig McKay <craig@frontburner.co.uk>
 *
 * Fortran Parser lexemes
 *
 * $Id$
 *
 * Who  When       Why
 * CAM  14-Jul-2009  10451 : File created.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

#define KEY_INTEGER              256
#define KEY_REAL                 257
#define KEY_COMPLEX              258
#define KEY_CHARACTER            259
#define KEY_LOGICAL              260
#define KEY_ABSTRACT             261
#define KEY_ALLOCATABLE          262
#define KEY_ALLOCATE             263
#define KEY_ASSIGNMENT           264
#define KEY_ASSIGN               265
#define KEY_ASSOCIATE            266
#define KEY_ASYNCHRONOUS         267
#define KEY_BACKSPACE            268
#define KEY_BLOCK                269
#define KEY_BLOCKDATA            270
#define KEY_CALL                 271
#define KEY_CASE                 272
#define KEY_CLASS                273
#define KEY_CLOSE                274
#define KEY_COMMON               275
#define KEY_CONTAINS             276
#define KEY_CONTINUE             277
#define KEY_CYCLE                278
#define KEY_DATA                 279
#define KEY_DEFAULT              280
#define KEY_DEALLOCATE           281
#define KEY_DEFERRED             282
#define KEY_DO                   283
#define KEY_DOUBLE               284
#define KEY_DOUBLEPRECISION      285
#define KEY_DOUBLECOMPLEX        286
#define KEY_ELEMENTAL            287
#define KEY_ELSE                 288
#define KEY_ELSEIF               289
#define KEY_ELSEWHERE            290
#define KEY_ENTRY                291
#define KEY_ENUM                 292
#define KEY_ENUMERATOR           293
#define KEY_EQUIVALENCE          294
#define KEY_EXIT                 295
#define KEY_EXTENDS              296
#define KEY_EXTERNAL             297
#define KEY_FILE                 298
#define KEY_FINAL                299
#define KEY_FLUSH                300
#define KEY_FORALL               301
#define KEY_FORMAT               302
#define KEY_FORMATTED            303
#define KEY_FUNCTION             304
#define KEY_GENERIC              305
#define KEY_GO                   306
#define KEY_GOTO                 307
#define KEY_IF                   308
#define KEY_IMPLICIT             309
#define KEY_IMPORT               310
#define KEY_IN                   311
#define KEY_INOUT                312
#define KEY_INTENT               313
#define KEY_INTERFACE            314
#define KEY_INTRINSIC            315
#define KEY_INQUIRE              316
#define KEY_MODULE               317
#define KEY_NAMELIST             318
#define KEY_NONE                 319
#define KEY_NON_INTRINSIC        320
#define KEY_NON_OVERRIDABLE      321
#define KEY_NOPASS               322
#define KEY_NULLIFY              323
#define KEY_ONLY                 324
#define KEY_OPEN                 325
#define KEY_OPERATOR             326
#define KEY_OPTIONAL             327
#define KEY_OUT                  328
#define KEY_PARAMETER            329
#define KEY_PASS                 330
#define KEY_PAUSE                331
#define KEY_POINTER              332
#define KEY_PRINT                333
#define KEY_PRECISION            334
#define KEY_PRIVATE              335
#define KEY_PROCEDURE            336
#define KEY_PROGRAM              337
#define KEY_PROTECTED            338
#define KEY_PUBLIC               339
#define KEY_PURE                 340
#define KEY_READ                 341
#define KEY_RECURSIVE            342
#define KEY_RESULT               343
#define KEY_RETURN               344
#define KEY_REWIND               345
#define KEY_SAVE                 346
#define KEY_SELECT               347
#define KEY_SELECTCASE           348
#define KEY_SELECTTYPE           349
#define KEY_SEQUENCE             350
#define KEY_STOP                 351
#define KEY_SUBROUTINE           352
#define KEY_TARGET               353
#define KEY_THEN                 354
#define KEY_TO                   355
#define KEY_TYPE                 356
#define KEY_UNFORMATTED          357
#define KEY_USE                  358
#define KEY_VALUE                359
#define KEY_VOLATILE             360
#define KEY_WAIT                 361
#define KEY_WHERE                362
#define KEY_WHILE                363
#define KEY_WRITE                364
#define KEY_ENDASSOCIATE         365
#define KEY_ENDBLOCK             366
#define KEY_ENDBLOCKDATA         367
#define KEY_ENDDO                368
#define KEY_ENDENUM              369
#define KEY_ENDFORALL            370
#define KEY_ENDFILE              371
#define KEY_ENDFUNCTION          372
#define KEY_ENDIF                373
#define KEY_ENDINTERFACE         374
#define KEY_ENDMODULE            375
#define KEY_ENDPROGRAM           376
#define KEY_ENDSELECT            377
#define KEY_ENDSUBROUTINE        378
#define KEY_ENDTYPE              379
#define KEY_ENDWHERE             380
#define KEY_END                  381
#define KEY_DIMENSION            382
#define KEY_KIND                 383
#define KEY_LEN                  384
#define KEY_BIND                 385
#define SYM_ASTERISK             386
#define SYM_COLON                387
#define SYM_COLONCOLON           388
#define SYM_COMMA                389
#define SYM_EQUALS               390
#define SYM_EQ_EQ                391
#define SYM_EQ_GT                392
#define SYM_GT                   393
#define SYM_GTEQ                 394
#define SYM_LT                   395
#define SYM_LTEQ                 396
#define SYM_LBRACKET             397
#define SYM_LPAREN               398
#define SYM_MINUS                399
#define SYM_PERCENT              400
#define SYM_PLUS                 401
#define SYM_POWER                402
#define SYM_SLASH                403
#define SYM_SLASHEQ              404
#define SYM_SLASHSLASH           405
#define SYM_RBRACKET             406
#define SYM_RPAREN               407
#define SYM_UNDERSCORE           408
