/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Essential Project Manager (EPM)
 * Copyright (c) 2004,2008 SourceCodeMetrics.com
 * Author Craig McKay <craig@frontburner.co.uk>
 *
 * XML Parser lexemes
 *
 * $Id$
 *
 * Who  When       Why
 * CAM  10-Dec-07   325 : File created.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

#define WSML_AND                           256
#define WSML_ARGUMENT                      257
#define WSML_ASSUMPTION                    258
#define WSML_ATOM                          259
#define WSML_ATTRIBUTE                     260
#define WSML_ATTRIBUTEDEFINITION           261
#define WSML_ATTRIBUTEID                  262
#define WSML_ATTRIBUTEVALUE                263
#define WSML_AXIOM                         264
#define WSML_CAPABILITY                    265
#define WSML_CHOREOGRAPHY                  266
#define WSML_CONCEPT                       267
#define WSML_CONJUNCTION                   268
#define WSML_CONSTRAINT                    269
#define WSML_DEFINEDBY                     270
#define WSML_DISJUNCTION                   271
#define WSML_EFFECT                        272
#define WSML_EQUIVALENT                    273
#define WSML_EXISTS                        274
#define WSML_FORALL                        275
#define WSML_FUNCTION                      276
#define WSML_GGMEDIATOR                    277
#define WSML_GOAL                          278
#define WSML_ID                            279
#define WSML_IMPLICATION                   280
#define WSML_IMPLIEDBY                     281
#define WSML_IMPLIEDBYLP                   282
#define WSML_IMPLIES                       283
#define WSML_IMPORTSONTOLOGY               284
#define WSML_INSTANCE                      285
#define WSML_INTERFACE                     286
#define WSML_INVERSEOF                     287
#define WSML_ISA                           288
#define WSML_LEFTHANDSIDE                  289
#define WSML_MAXCARDINALITY                290
#define WSML_MEMBEROF                      291
#define WSML_MINCARDINALITY                292
#define WSML_MOLECULE                      293
#define WSML_NAF                           294
#define WSML_NEG                           295
#define WSML_NONFUNCTIONALPROPERTIES       296
#define WSML_ONTOLOGY                      297
#define WSML_OOMEDIATOR                    298
#define WSML_OR                            299
#define WSML_ORCHESTRATION                 300
#define WSML_PARAMETER                     301
#define WSML_PARAMETERS                    302
#define WSML_POSTCONDITION                 303
#define WSML_PRECONDITION                  304
#define WSML_PREDICATE                     305
#define WSML_QUANTIFICATION                306
#define WSML_RANGE                         307
#define WSML_REFLEXIVE                     308
#define WSML_RELATION                      309
#define WSML_RELATIONINSTANCE              310
#define WSML_RIGHTHANDSIDE                 311
#define WSML_SHAREDVARIABLES               312
#define WSML_SOURCE                        313
#define WSML_SUPERCONCEPT                  314
#define WSML_SUPERRELATION                 315
#define WSML_SYMMETRIC                     316
#define WSML_TARGET                        317
#define WSML_TERM                          318
#define WSML_TRANSITIVE                    319
#define WSML_TYPE                          320
#define WSML_USESMEDIATOR                  321
#define WSML_USESSERVICE                   322
#define WSML_VALUE                         323
#define WSML_VERSION                       324
#define WSML_WEBSERVICE                    325
#define WSML_WGMEDIATOR                    326
#define WSML_WSML                          327
#define WSML_WWMEDIATOR                    328
#define XSD_ALL                            329
#define XSD_ANYATTRIBUTE                   330
#define XSD_ATTRIBUTE                      331
#define XSD_CHOICE                         332
#define XSD_COMPLEXTYPE                    333
#define XSD_ELEMENT                        334
#define XSD_ENUMERATION                    335
#define XSD_FRACTIONDIGITS                 336
#define XSD_LENGTH                         337
#define XSD_MAXEXCLUSIVE                   338
#define XSD_MAXINCLUSIVE                   339
#define XSD_MAXLENGTH                      340
#define XSD_MINEXCLUSIVE                   341
#define XSD_MININCLUSIVE                   342
#define XSD_MINLENGTH                      343
#define XSD_PATTERN                        344
#define XSD_RESTRICTION                    345
#define XSD_SCHEMA                         346
#define XSD_SIMPLECONTENT                  347
#define XSD_SIMPLETYPE                     348
#define XSD_TOTALDIGITS                    349
#define XSL_APPLY_IMPORTS                  350
#define XSL_APPLY_TEMPLATES                351
#define XSL_ATTRIBUTE                      352
#define XSL_ATTRIBUTE_SET                  353
#define XSL_CALL_TEMPLATE                  354
#define XSL_CHOOSE                         355
#define XSL_COMMENT                        356
#define XSL_COPY                           357
#define XSL_COPY_OF                        358
#define XSL_DECIMAL_FORMAT                 359
#define XSL_ELEMENT                        360
#define XSL_FALLBACK                       361
#define XSL_FOR_EACH                       362
#define XSL_IF                             363
#define XSL_IMPORT                         364
#define XSL_INCLUDE                        365
#define XSL_KEY                            366
#define XSL_MESSAGE                        367
#define XSL_NAMESPACE_ALIAS                368
#define XSL_NUMBER                         369
#define XSL_OTHERWISE                      370
#define XSL_OUTPUT                         371
#define XSL_PARAM                          372
#define XSL_PRESERVE_SPACE                 373
#define XSL_PROCESSING_INSTRUCTION         374
#define XSL_SORT                           375
#define XSL_STRIP_SPACE                    376
#define XSL_STYLESHEET                     377
#define XSL_TEMPLATE                       378
#define XSL_TEXT                           379
#define XSL_TRANSFORM                      380
#define XSL_VALUE_OF                       381
#define XSL_VARIABLE                       382
#define XSL_WHEN                           383
#define XSL_WITH_PARAM                     384
