<table border=0 cellpadding=4 cellspacing=4>

<tr>
  <td class="annot" valign=top><img class=box src="img/dolphin1.jpg"><br>Dolphin</td>
  <td class="main"><p>some text will go here... some text will go here... some text will go here...
  some text will go here... some text will go here... some text will go here...
  some text will go here... some text will go here... some text will go here...
  some text will go here... some text will go here... some text will go here... some text will go here... </p>

  <p>some text will go here... some text will go here... some text will go here...
  some text will go here... some text will go here... some text will go here...
  some text will go here... some text will go here... some text will go here...
  some text will go here... some text will go here... some text will go here... some text will go here... </p></td>

  </tr><tr>

  <td class="main" colspan=2><p>some text will go here... some text will go here... some text will go here...
  some text will go here... some text will go here... some text will go here...
  some text will go here... some text will go here... some text will go here...
  some text will go here... some text will go here... some text will go here... some text will go here... </p>

  <p>some text will go here... some text will go here... some text will go here...
  some text will go here... some text will go here... some text will go here...
  some text will go here... some text will go here... some text will go here...
  some text will go here... some text will go here... some text will go here... some text will go here... </p>

  </td>
</tr>

</table>
