s/j_comments/j_comments_jsp/g
s/c_comments/c_comments_jsp/g
s/cpp_comments/cpp_comments_jsp/g
s/com_loc/com_loc_jsp/g
s/prev_com_line/prev_com_line_jsp/g
s/comment_skip/comment_skip_jsp/g
s/lexclear/lexclear_jsp/g
s/eat_eol/eat_eol_jsp/g
s/nsemi/nsemi_jsp/g
s/operands/operands_jsp/g
s/operators/operators_jsp/g
s/sloc/sloc_jsp/g
s/slnat/slnat_jsp/g
s/sltag/sltag_jsp/g
s/slhtm/slhtm_jsp/g
s/slscr/slscr_jsp/g
s/store_operand/store_operand_jsp/g
s/store_operator/store_operator_jsp/g
s/yy_buffer_state/yy_buffer_state_jsp/g
s/yy_load_buffer_state/yy_load_buffer_state_jsp/g
s/yy_switch_to_buffer/yy_switch_to_buffer_jsp/g
s/yyin/yyin_jsp/g
s/yyleng/yyleng_jsp/g
s/yylex/yylex_jsp/g
s/yyout/yyout_jsp/g
s/yyrestart/yyrestart_jsp/g
s/yytext/yytext_jsp/g
s/yywrap/yywrap_jsp/g
/#include <unistd.h>/d
s/isatty(/_isatty(/g
s/fileno(/_fileno(/g
s/read(/_read(/g
