s/j_comments/j_comments_pb/g
s/c_comments/c_comments_pb/g
s/cpp_comments/cpp_comments_pb/g
s/com_loc/com_loc_pb/g
s/prev_com_line/prev_com_line_pb/g
s/comment_skip/comment_skip_pb/g
s/lexclear/lexclear_pb/g
s/nsemi/nsemi_pb/g
s/operands/operands_pb/g
s/operators/operators_pb/g
s/sloc/sloc_pb/g
s/slnat/slnat_pb/g
s/slhtm/slhtm_pb/g
s/slscr/slscr_pb/g
s/store_operand/store_operand_pb/g
s/store_operator/store_operator_pb/g
s/yy_buffer_state/yy_buffer_state_pb/g
s/yy_load_buffer_state/yy_load_buffer_state_pb/g
s/yy_switch_to_buffer/yy_switch_to_buffer_pb/g
s/yyin/yyin_pb/g
s/yyleng/yyleng_pb/g
s/yylex/yylex_pb/g
s/yyout/yyout_pb/g
s/yyrestart/yyrestart_pb/g
s/yytext/yytext_pb/g
s/yywrap/yywrap_pb/g
/#include <unistd.h>/d
s/isatty(/_isatty(/g
s/fileno(/_fileno(/g
s/read(/_read(/g
