s/j_comments/j_comments_sh/g
s/c_comments/c_comments_sh/g
s/cpp_comments/cpp_comments_sh/g
s/com_loc/com_loc_sh/g
s/prev_com_line/prev_com_line_sh/g
s/comment_skip/comment_skip_sh/g
s/lexclear/lexclear_sh/g
s/eat_eol/eat_eol_sh/g
s/nsemi/nsemi_sh/g
s/operands/operands_sh/g
s/operators/operators_sh/g
s/sloc/sloc_sh/g
s/slnat/slnat_sh/g
s/sltag/sltag_sh/g
s/slhtm/slhtm_sh/g
s/slscr/slscr_sh/g
s/store_operand/store_operand_sh/g
s/store_operator/store_operator_sh/g
s/yy_buffer_state/yy_buffer_state_sh/g
s/yy_load_buffer_state/yy_load_buffer_state_sh/g
s/yy_switch_to_buffer/yy_switch_to_buffer_sh/g
s/yyin/yyin_sh/g
s/yyleng/yyleng_sh/g
s/yylex/yylex_sh/g
s/yyout/yyout_sh/g
s/yyrestart/yyrestart_sh/g
s/yytext/yytext_sh/g
s/yywrap/yywrap_sh/g
s/string_literal/string_literal_sh/g
/#include <unistd.h>/d
s/isatty(/_isatty(/g
s/fileno(/_fileno(/g
s/read(/_read(/g
