s/j_comments/j_comments_ss/g
s/c_comments/c_comments_ss/g
s/cpp_comments/cpp_comments_ss/g
s/com_loc/com_loc_ss/g
s/prev_com_line/prev_com_line_ss/g
s/comment_skip/comment_skip_ss/g
s/lexclear/lexclear_ss/g
s/eat_eol/eat_eol_ss/g
s/nsemi/nsemi_ss/g
s/operands/operands_ss/g
s/operators/operators_ss/g
s/sloc/sloc_ss/g
s/slnat/slnat_ss/g
s/sltag/sltag_ss/g
s/slhtm/slhtm_ss/g
s/slscr/slscr_ss/g
s/store_operand/store_operand_ss/g
s/store_operator/store_operator_ss/g
s/yy_buffer_state/yy_buffer_state_ss/g
s/yy_load_buffer_state/yy_load_buffer_state_ss/g
s/yy_switch_to_buffer/yy_switch_to_buffer_ss/g
s/yyin/yyin_ss/g
s/yyleng/yyleng_ss/g
s/yylex/yylex_ss/g
s/yyout/yyout_ss/g
s/yyrestart/yyrestart_ss/g
s/yytext/yytext_ss/g
s/yywrap/yywrap_ss/g
/#include <unistd.h>/d
s/isatty(/_isatty(/g
s/fileno(/_fileno(/g
s/read(/_read(/g
