s/j_comments/j_comments_uc/g
s/c_comments/c_comments_uc/g
s/cpp_comments/cpp_comments_uc/g
s/com_loc/com_loc_uc/g
s/comment_skip/comment_skip_uc/g
s/lexclear/lexclear_uc/g
s/nsemi/nsemi_uc/g
s/ploc_count/ploc_count_uc/g
s/operands/operands_uc/g
s/operators/operators_uc/g
s/sloc/sloc_uc/g
s/store_operand/store_operand_uc/g
s/store_operator/store_operator_uc/g
s/yy_buffer_state/yy_buffer_state_uc/g
s/yy_load_buffer_state/yy_load_buffer_state_uc/g
s/yy_switch_to_buffer/yy_switch_to_buffer_uc/g
s/yyin/yyin_uc/g
s/yyleng/yyleng_uc/g
s/yylex/yylex_uc/g
s/yyout/yyout_uc/g
s/yyrestart/yyrestart_uc/g
s/yytext/yytext_uc/g
s/yywrap/yywrap_uc/g
s/string_literal/string_literal_uc/g
/#include <unistd.h>/d
s/isatty(/_isatty(/g
s/fileno(/_fileno(/g
s/read(/_read(/g
