s/j_comments/j_comments_vhdl/g
s/c_comments/c_comments_vhdl/g
s/cpp_comments/cpp_comments_vhdl/g
s/com_loc/com_loc_vhdl/g
s/prev_com_line/prev_com_line_vhdl/g
s/comment_skip/comment_skip_vhdl/g
s/lexclear/lexclear_vhdl/g
s/nsemi/nsemi_vhdl/g
s/operands/operands_vhdl/g
s/operators/operators_vhdl/g
s/sloc/sloc_vhdl/g
s/store_operand/store_operand_vhdl/g
s/store_operator/store_operator_vhdl/g
s/yy_buffer_state/yy_buffer_state_vhdl/g
s/yy_load_buffer_state/yy_load_buffer_state_vhdl/g
s/yy_switch_to_buffer/yy_switch_to_buffer_vhdl/g
s/yyin/yyin_vhdl/g
s/yyleng/yyleng_vhdl/g
s/yylex/yylex_vhdl/g
s/yyout/yyout_vhdl/g
s/yyrestart/yyrestart_vhdl/g
s/yytext/yytext_vhdl/g
s/yywrap/yywrap_vhdl/g
s/string_literal/string_literal_vhdl/g
/#include <unistd.h>/d
s/isatty(/_isatty(/g
s/fileno(/_fileno(/g
s/read(/_read(/g
