s/j_comments/j_comments_asp/g
s/c_comments/c_comments_asp/g
s/cpp_comments/cpp_comments_asp/g
s/com_loc/com_loc_asp/g
s/prev_com_line/prev_com_line_asp/g
s/comment_skip/comment_skip_asp/g
s/lexclear/lexclear_asp/g
s/eat_eol/eat_eol_asp/g
s/nsemi/nsemi_asp/g
s/operands/operands_asp/g
s/operators/operators_asp/g
s/sloc/sloc_asp/g
s/slnat/slnat_asp/g
s/sltag/sltag_asp/g
s/slhtm/slhtm_asp/g
s/slscr/slscr_asp/g
s/store_operand/store_operand_asp/g
s/store_operator/store_operator_asp/g
s/yy_buffer_state/yy_buffer_state_asp/g
s/yy_load_buffer_state/yy_load_buffer_state_asp/g
s/yy_switch_to_buffer/yy_switch_to_buffer_asp/g
s/yyin/yyin_asp/g
s/yyleng/yyleng_asp/g
s/yylex/yylex_asp/g
s/yyout/yyout_asp/g
s/yyrestart/yyrestart_asp/g
s/yytext/yytext_asp/g
s/yywrap/yywrap_asp/g
s/string_literal/string_literal_asp/g
/#include <unistd.h>/d
s/isatty(/_isatty(/g
s/fileno(/_fileno(/g
s/read(/_read(/g
