s/j_comments/j_comments_ay/g
s/c_comments/c_comments_ay/g
s/cpp_comments/cpp_comments_ay/g
s/com_loc/com_loc_ay/g
s/prev_com_line/prev_com_line_ay/g
s/comment_skip/comment_skip_ay/g
s/lexclear/lexclear_ay/g
s/eat_eol/eat_eol_ay/g
s/nsemi/nsemi_ay/g
s/operands/operands_ay/g
s/operators/operators_ay/g
s/sloc/sloc_ay/g
s/slnat/slnat_ay/g
s/sltag/sltag_ay/g
s/slhtm/slhtm_ay/g
s/slscr/slscr_ay/g
s/store_operand/store_operand_ay/g
s/store_operator/store_operator_ay/g
s/yy_buffer_state/yy_buffer_state_ay/g
s/yy_load_buffer_state/yy_load_buffer_state_ay/g
s/yy_switch_to_buffer/yy_switch_to_buffer_ay/g
s/yyin/yyin_ay/g
s/yyleng/yyleng_ay/g
s/yylex/yylex_ay/g
s/yyout/yyout_ay/g
s/yyrestart/yyrestart_ay/g
s/yytext/yytext_ay/g
s/yywrap/yywrap_ay/g
s/string_literal/string_literal_ay/g
/#include <unistd.h>/d
s/isatty(/_isatty(/g
s/fileno(/_fileno(/g
s/read(/_read(/g
