s/j_comments/j_comments_c/g
s/c_comments/c_comments_c/g
s/cpp_comments/cpp_comments_c/g
s/com_loc/com_loc_c/g
s/prev_com_line/prev_com_line_c/g
s/comment_skip/comment_skip_c/g
s/lexclear/lexclear_c/g
s/nsemi/nsemi_c/g
s/operands/operands_c/g
s/operators/operators_c/g
s/sloc/sloc_c/g
s/store_operand/store_operand_c/g
s/yy_buffer_state/yy_buffer_state_c/g
s/yy_load_buffer_state/yy_load_buffer_state_c/g
s/yy_switch_to_buffer/yy_switch_to_buffer_c/g
s/yyin/yyin_c/g
s/yyleng/yyleng_c/g
s/yylex/yylex_c/g
s/yyout/yyout_c/g
s/yyrestart/yyrestart_c/g
s/yytext/yytext_c/g
s/yywrap/yywrap_c/g
s/string_literal/string_literal_cs/g
/#include <unistd.h>/d
