s/j_comments/j_comments_php/g
s/c_comments/c_comments_php/g
s/cpp_comments/cpp_comments_php/g
s/com_loc/com_loc_php/g
s/prev_com_line/prev_com_line_php/g
s/comment_skip/comment_skip_php/g
s/lexclear/lexclear_php/g
s/nsemi/nsemi_php/g
s/operands/operands_php/g
s/operators/operators_php/g
s/sloc/sloc_php/g
s/slnat/slnat_php/g
s/slhtm/slhtm_php/g
s/slscr/slscr_php/g
s/store_operand/store_operand_php/g
s/store_operator/store_operator_php/g
s/yy_buffer_state/yy_buffer_state_php/g
s/yy_load_buffer_state/yy_load_buffer_state_php/g
s/yy_switch_to_buffer/yy_switch_to_buffer_php/g
s/yyin/yyin_php/g
s/yyleng/yyleng_php/g
s/yylex/yylex_php/g
s/yyout/yyout_php/g
s/yyrestart/yyrestart_php/g
s/yytext/yytext_php/g
s/yywrap/yywrap_php/g
/#include <unistd.h>/d
