s/j_comments/j_comments_vb/g
s/c_comments/c_comments_vb/g
s/cpp_comments/cpp_comments_vb/g
s/com_loc/com_loc_vb/g
s/prev_com_line/prev_com_line_vb/g
s/comment_skip/comment_skip_vb/g
s/lexclear/lexclear_vb/g
s/nsemi/nsemi_vb/g
s/operands/operands_vb/g
s/operators/operators_vb/g
s/sloc/sloc_vb/g
s/store_operand/store_operand_vb/g
s/store_operator/store_operator_vb/g
s/yy_buffer_state/yy_buffer_state_vb/g
s/yy_load_buffer_state/yy_load_buffer_state_vb/g
s/yy_switch_to_buffer/yy_switch_to_buffer_vb/g
s/yyin/yyin_vb/g
s/yyleng/yyleng_vb/g
s/yylex/yylex_vb/g
s/yyout/yyout_vb/g
s/yyrestart/yyrestart_vb/g
s/yytext/yytext_vb/g
s/yywrap/yywrap_vb/g
s/string_literal/string_literal_vb/g
/#include <unistd.h>/d
