s/j_comments/j_comments_wb/g
s/c_comments/c_comments_wb/g
s/cpp_comments/cpp_comments_wb/g
s/com_loc/com_loc_wb/g
s/prev_com_line/prev_com_line_wb/g
s/comment_skip/comment_skip_wb/g
s/lexclear/lexclear_wb/g
s/nsemi/nsemi_wb/g
s/operands/operands_wb/g
s/operators/operators_wb/g
s/sloc/sloc_wb/g
s/store_operand/store_operand_wb/g
s/store_operator/store_operator_wb/g
s/yy_buffer_state/yy_buffer_state_wb/g
s/yy_load_buffer_state/yy_load_buffer_state_wb/g
s/yy_switch_to_buffer/yy_switch_to_buffer_wb/g
s/yyin/yyin_wb/g
s/yyleng/yyleng_wb/g
s/yylex/yylex_wb/g
s/yyout/yyout_wb/g
s/yyrestart/yyrestart_wb/g
s/yytext/yytext_wb/g
s/yywrap/yywrap_wb/g
s/string_literal/string_literal_wb/g
/#include <unistd.h>/d
s/isatty(/_isatty(/g
s/fileno(/_fileno(/g
s/read(/_read(/g
