/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Essential Project Manager (EPM)
 * Copyright (c) 2004,2008 PowerSoftware.com
 * Author Craig McKay <craig@frontburner.co.uk>
 *
 * PHP Parser lexemes
 *
 * $Id$
 *
 * Who  When       Why
 * CAM  04-Nov-06   301 : File created.
 * CAM  28-Nov-07   323 : Added HTM and PHP lexemes.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

#define HTM_ALIGN                256
#define HTM_ALT                  257
#define HTM_APPLET               258
#define HTM_AREA                 259
#define HTM_A                    260
#define HTM_BACKGROUND           261
#define HTM_BGCOLOR              262
#define HTM_BLOCKQUOTE           263
#define HTM_BODY                 264
#define HTM_BORDERCOLOR          265
#define HTM_BORDER               266
#define HTM_BR                   267
#define HTM_BUTTON               268
#define HTM_B                    269
#define HTM_CENTER               270
#define HTM_CHECKED              271
#define HTM_CLASS                272
#define HTM_CODE                 273
#define HTM_COLOR                274
#define HTM_COLS                 275
#define HTM_COLSPAN              276
#define HTM_DIV                  277
#define HTM_EMBED                278
#define HTM_FACE                 279
#define HTM_FONT                 280
#define HTM_FORM                 281
#define HTM_FRAMEBORDER          282
#define HTM_FRAMESET             283
#define HTM_FRAMESPACING         284
#define HTM_FRAME                285
#define HTM_H1                   286
#define HTM_H2                   287
#define HTM_H3                   288
#define HTM_H4                   289
#define HTM_H5                   290
#define HTM_H6                   291
#define HTM_HEAD                 292
#define HTM_HEIGHT               293
#define HTM_HIDDEN               294
#define HTM_HR                   295
#define HTM_HREF                 296
#define HTM_HTML                 297
#define HTM_HTTPEQUIV            298
#define HTM_ID                   299
#define HTM_IFRAME               300
#define HTM_ILAYER               301
#define HTM_IMG                  302
#define HTM_INPUT                303
#define HTM_LABEL                304
#define HTM_LANGUAGE             305
#define HTM_LANG                 306
#define HTM_LAYER                307
#define HTM_LEFTMARGIN           308
#define HTM_LI                   309
#define HTM_LINK                 310
#define HTM_MAP                  311
#define HTM_MARGINHEIGHT         312
#define HTM_MARGINWIDTH          313
#define HTM_META                 314
#define HTM_METHOD               315
#define HTM_MULTIPLE             316
#define HTM_NAME                 317
#define HTM_OBJECT               318
#define HTM_OL                   319
#define HTM_OPTGROUP             320
#define HTM_OPTION               321
#define HTM_PARAM                322
#define HTM_PRE                  323
#define HTM_PUBLIC               324
#define HTM_P                    325
#define HTM_READONLY             326
#define HTM_ROWSPAN              327
#define HTM_SCROLLING            328
#define HTM_SCROLL               329
#define HTM_SELECTED             330
#define HTM_SELECT               331
#define HTM_SIZE                 332
#define HTM_SMALL                333
#define HTM_SPAN                 334
#define HTM_SRC                  335
#define HTM_STYLE                336
#define HTM_SUB                  337
#define HTM_SUP                  338
#define HTM_TABLE                339
#define HTM_TD                   340
#define HTM_TEXTAREA             341
#define HTM_TEXT                 342
#define HTM_TH                   343
#define HTM_TITLE                344
#define HTM_TR                   345
#define HTM_UL                   346
#define HTM_URL                  347
#define HTM_URN                  348
#define HTM_USEMAP               349
#define HTM_VALIGN               350
#define HTM_VALUE                351
#define HTM_WIDTH                352
#define PHP__CLASS               353
#define PHP__FILE                354
#define PHP__FUNCTION            355
#define PHP__LINE                356
#define PHP__METHOD              357
#define PHP_ABSTRACT             358
#define PHP_AND                  359
#define PHP_ARRAY                360
#define PHP_AS                   361
#define PHP_BREAK                362
#define PHP_CASE                 363
#define PHP_CATCH                364
#define PHP_CFUNCTION            365
#define PHP_CLASS                366
#define PHP_CLONE                367
#define PHP_CONST                368
#define PHP_CONTINUE             369
#define PHP_DECLARE              370
#define PHP_DEFAULT              371
#define PHP_DIE                  372
#define PHP_DO                   373
#define PHP_ECHO                 374
#define PHP_ELSE                 375
#define PHP_ELSEIF               376
#define PHP_EMPTY                377
#define PHP_ENDDECLARE           378
#define PHP_ENDFOR               379
#define PHP_ENDFOREACH           380
#define PHP_ENDIF                381
#define PHP_ENDSWITCH            382
#define PHP_ENDWHILE             383
#define PHP_EVAL                 384
#define PHP_EXCEPTION            385
#define PHP_EXIT                 386
#define PHP_EXTENDS              387
#define PHP_FINAL                389
#define PHP_FOR                  390
#define PHP_FOREACH              391
#define PHP_FUNCTION             392
#define PHP_GLOBAL               393
#define PHP_IF                   394
#define PHP_IMPLEMENTS           395
#define PHP_INCLUDE              396
#define PHP_INCLUDE_ONCE         397
#define PHP_INTERFACE            398
#define PHP_ISSET                399
#define PHP_LIST                 400
#define PHP_NEW                  401
#define PHP_OLD_FUNCTION         402
#define PHP_OR                   403
#define PHP_PHP_USER_FILTER      404
#define PHP_PRINT                405
#define PHP_PRIVATE              406
#define PHP_PROTECTED            407
#define PHP_PUBLIC               408
#define PHP_REQUIRE              409
#define PHP_REQUIRE_ONCE         410
#define PHP_RETURN               411
#define PHP_STATIC               412
#define PHP_SWITCH               413
#define PHP_THROW                414
#define PHP_TRY                  415
#define PHP_UNSET                416
#define PHP_USE                  417
#define PHP_VAR                  418
#define PHP_WHILE                419
#define PHP_XOR                  420
