s/j_comments/j_comments_tx/g
s/c_comments/c_comments_tx/g
s/cpp_comments/cpp_comments_tx/g
s/com_loc/com_loc_tx/g
s/prev_com_line/prev_com_line_tx/g
s/comment_skip/comment_skip_tx/g
s/lexclear/lexclear_tx/g
s/eat_eol/eat_eol_tx/g
s/nsemi/nsemi_tx/g
s/operands/operands_tx/g
s/operators/operators_tx/g
s/sloc/sloc_tx/g
s/slnat/slnat_tx/g
s/sltag/sltag_tx/g
s/slhtm/slhtm_tx/g
s/slscr/slscr_tx/g
s/store_operand/store_operand_tx/g
s/store_operator/store_operator_tx/g
s/yy_buffer_state/yy_buffer_state_tx/g
s/yy_load_buffer_state/yy_load_buffer_state_tx/g
s/yy_switch_to_buffer/yy_switch_to_buffer_tx/g
s/yyin/yyin_tx/g
s/yyleng/yyleng_tx/g
s/yylex/yylex_tx/g
s/yyout/yyout_tx/g
s/yyrestart/yyrestart_tx/g
s/yytext/yytext_tx/g
s/yywrap/yywrap_tx/g
s/string_literal/string_literal_tx/g
/#include <unistd.h>/d
s/isatty(/_isatty(/g
s/fileno(/_fileno(/g
s/read(/_read(/g
