/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Essential Project Manager (EPM)
 * Copyright (c) 2009 PowerSoftware.com
 * Author Craig McKay <craig@frontburner.co.uk>
 *
 * CSS parser
 *
 * $Id$
 *
 * Who  When         Why
 * CAM  12-Aug-2009  10450 : File created.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

#define CSS_AZIMUTH                     256
#define CSS_BACKGROUND                  257
#define CSS_BACKGROUNDATTACHMENT        258
#define CSS_BACKGROUNDCOLOR             259
#define CSS_BACKGROUNDIMAGE             260
#define CSS_BACKGROUNDPOSITION          261
#define CSS_BACKGROUNDREPEAT            262
#define CSS_BORDER                      263
#define CSS_BORDERBOTTOM                264
#define CSS_BORDERBOTTOMCOLOR           265
#define CSS_BORDERBOTTOMSTYLE           266
#define CSS_BORDERBOTTOMWIDTH           267
#define CSS_BORDERCOLLAPSE              268
#define CSS_BORDERCOLOR                 269
#define CSS_BORDERLEFT                  270
#define CSS_BORDERLEFTCOLOR             271
#define CSS_BORDERLEFTSTYLE             272
#define CSS_BORDERLEFTWIDTH             273
#define CSS_BORDERRIGHT                 274
#define CSS_BORDERRIGHTCOLOR            275
#define CSS_BORDERRIGHTSTYLE            276
#define CSS_BORDERRIGHTWIDTH            277
#define CSS_BORDERSPACING               278
#define CSS_BORDERSTYLE                 279
#define CSS_BORDERTOP                   280
#define CSS_BORDERTOPCOLOR              281
#define CSS_BORDERTOPSTYLE              282
#define CSS_BORDERTOPWIDTH              283
#define CSS_BORDERWIDTH                 284
#define CSS_BOTTOM                      285
#define CSS_CAPTIONSIDE                 286
#define CSS_CLEAR                       287
#define CSS_CLIP                        288
#define CSS_COLOR                       289
#define CSS_CONTENT                     290
#define CSS_COUNTERINCREMENT            291
#define CSS_COUNTERRESET                292
#define CSS_CUE                         293
#define CSS_CUEAFTER                    294
#define CSS_CUEBEFORE                   295
#define CSS_CURSOR                      296
#define CSS_DIRECTION                   297
#define CSS_DISPLAY                     298
#define CSS_ELEVATION                   299
#define CSS_EMPTYCELLS                  300
#define CSS_FLOAT                       301
#define CSS_FONT                        302
#define CSS_FONTFAMILY                  303
#define CSS_FONTSIZE                    304
#define CSS_FONTSTYLE                   305
#define CSS_FONTVARIANT                 306
#define CSS_FONTWEIGHT                  307
#define CSS_HEIGHT                      308
#define CSS_LEFT                        309
#define CSS_LETTERSPACING               310
#define CSS_LINEHEIGHT                  311
#define CSS_LISTSTYLE                   312
#define CSS_LISTSTYLEIMAGE              313
#define CSS_LISTSTYLEPOSITION           314
#define CSS_LISTSTYLETYPE               315
#define CSS_MARGIN                      316
#define CSS_MARGINBOTTOM                317
#define CSS_MARGINLEFT                  318
#define CSS_MARGINRIGHT                 319
#define CSS_MARGINTOP                   320
#define CSS_MAXHEIGHT                   321
#define CSS_MAXWIDTH                    322
#define CSS_MINHEIGHT                   323
#define CSS_MINWIDTH                    324
#define CSS_ORPHANS                     325
#define CSS_OUTLINE                     326
#define CSS_OUTLINECOLOR                327
#define CSS_OUTLINESTYLE                328
#define CSS_OUTLINEWIDTH                329
#define CSS_OVERFLOW                    330
#define CSS_PADDING                     331
#define CSS_PADDINGBOTTOM               332
#define CSS_PADDINGLEFT                 333
#define CSS_PADDINGRIGHT                334
#define CSS_PADDINGTOP                  335
#define CSS_PAGEBREAKAFTER              336
#define CSS_PAGEBREAKBEFORE             337
#define CSS_PAGEBREAKINSIDE             338
#define CSS_PAUSE                       339
#define CSS_PAUSEAFTER                  340
#define CSS_PAUSEBEFORE                 341
#define CSS_PITCH                       342
#define CSS_PITCHRANGE                  343
#define CSS_PLAYDURING                  344
#define CSS_POSITION                    345
#define CSS_QUOTES                      346
#define CSS_RICHNESS                    347
#define CSS_RIGHT                       348
#define CSS_SPEAK                       349
#define CSS_SPEAKHEADER                 350
#define CSS_SPEAKNUMERAL                351
#define CSS_SPEAKPUNCTUATION            352
#define CSS_SPEECHRATE                  353
#define CSS_STRESS                      354
#define CSS_TABLELAYOUT                 355
#define CSS_TEXTALIGN                   356
#define CSS_TEXTDECORATION              357
#define CSS_TEXTINDENT                  358
#define CSS_TEXTTRANSFORM               359
#define CSS_TOP                         360
#define CSS_UNICODEBIDI                 361
#define CSS_VERTICALALIGN               362
#define CSS_VISIBILITY                  363
#define CSS_VOICEFAMILY                 364
#define CSS_VOLUME                      365
#define CSS_WHITESPACE                  366
#define CSS_WIDOWS                      367
#define CSS_WIDTH                       368
#define CSS_WORDSPACING                 369
#define CSS_ZINDEX                      370
#define HTM_A                           371
#define HTM_ACTION                      372
#define HTM_ALINK                       373
#define HTM_AREA                        374
#define HTM_B                           375
#define HTM_BIG                         376
#define HTM_BLINK                       377
#define HTM_BLOCKQUOTE                  378
#define HTM_BODY                        379
#define HTM_BR                          380
#define HTM_BUTTON                      381
#define HTM_CAPTION                     382
#define HTM_DD                          383
#define HTM_DIV                         384
#define HTM_DL                          385
#define HTM_DT                          386
#define HTM_EM                          387
#define HTM_FORM                        388
#define HTM_H1                          389
#define HTM_H2                          390
#define HTM_H3                          391
#define HTM_H4                          392
#define HTM_H5                          393
#define HTM_H6                          394
#define HTM_HEAD                        395
#define HTM_HR                          396
#define HTM_IFRAME                      397
#define HTM_IMG                         398
#define HTM_INPUT                       399
#define HTM_LABEL                       400
#define HTM_LI                          401
#define HTM_LINK                        402
#define HTM_LOOP                        403
#define HTM_MAP                         404
#define HTM_OBJECT                      405
#define HTM_OL                          406
#define HTM_OPTGROUP                    407
#define HTM_OPTION                      408
#define HTM_P                           409
#define HTM_PRE                         410
#define HTM_SELECT                      411
#define HTM_SELECTED                    412
#define HTM_SERVER                      413
#define HTM_SHAPE                       414
#define HTM_SMALL                       415
#define HTM_SOUND                       416
#define HTM_SPACER                      417
#define HTM_START                       418
#define HTM_STRIKE                      419
#define HTM_STRONG                      420
#define HTM_STYLE                       421
#define HTM_SUB                         422
#define HTM_SUP                         423
#define HTM_TABLE                       424
#define HTM_TBODY                       425
#define HTM_TD                          426
#define HTM_TEXT                        427
#define HTM_TEXTAREA                    428
#define HTM_TFOOT                       429
#define HTM_TH                          430
#define HTM_THEAD                       431
#define HTM_TR                          432
#define HTM_TT                          433
#define HTM_UL                          434
